/**
 * Shared helpers for the npm scripts: .env.local loading, secret generation
 * and a one-line description of the configured storage. No framework imports;
 * runs under tsx before Next.js is started.
 */
import { randomBytes } from "node:crypto";
import { appendFileSync, existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { DEFAULTS, ENV } from "@/lib/contracts";

export const ENV_FILE = ".env.local";

/** Minimal dotenv parser: KEY=value, optional `export`, quotes, # comments. */
export function parseDotEnv(text: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const match = /^(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/.exec(line);
    if (!match) continue;
    let value = match[2].trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    } else {
      const hash = value.indexOf(" #");
      if (hash >= 0) value = value.slice(0, hash).trim();
    }
    out[match[1]] = value;
  }
  return out;
}

/**
 * Loads .env.local into process.env without overriding variables that are
 * already set (the same precedence Next.js uses). Returns what the file held.
 */
export function loadDotEnvLocal(dir: string = process.cwd()): Record<string, string> {
  const file = path.join(dir, ENV_FILE);
  if (!existsSync(file)) return {};
  const parsed = parseDotEnv(readFileSync(file, "utf8"));
  for (const [key, value] of Object.entries(parsed)) {
    if (process.env[key] === undefined) process.env[key] = value;
  }
  return parsed;
}

/** Bearer token shape shown in the console as "hw_… (67 characters)". */
export function generateToken(): string {
  return `hw_${randomBytes(32).toString("hex")}`;
}

export function generateAdminSecret(): string {
  return randomBytes(24).toString("base64url");
}

export interface GeneratedSecret {
  key: string;
  value: string;
}

/**
 * Makes sure HOUSEWARDEN_TOKEN and HOUSEWARDEN_ADMIN_SECRET exist and are long
 * enough. Missing ones are generated, appended to .env.local and exported to
 * process.env. Returns the ones generated so the caller can print them once.
 */
export function ensureSecrets(dir: string = process.cwd()): GeneratedSecret[] {
  const file = path.join(dir, ENV_FILE);
  const generated: GeneratedSecret[] = [];
  const wanted: { key: string; min: number; make: () => string }[] = [
    { key: ENV.TOKEN, min: 16, make: generateToken },
    { key: ENV.ADMIN_SECRET, min: 8, make: generateAdminSecret },
  ];
  const lines: string[] = [];
  for (const { key, min, make } of wanted) {
    const current = process.env[key];
    if (current && current.length >= min) continue;
    const value = make();
    process.env[key] = value;
    generated.push({ key, value });
    lines.push(`${key}=${value}`);
  }
  if (lines.length > 0) {
    if (!existsSync(file)) {
      writeFileSync(file, `# Housewarden secrets, generated by npm run dev. Keep this file private.\n`, "utf8");
    }
    const existing = readFileSync(file, "utf8");
    const prefix = existing.length > 0 && !existing.endsWith("\n") ? "\n" : "";
    appendFileSync(file, `${prefix}${lines.join("\n")}\n`, "utf8");
  }
  return generated;
}

export interface StorageInfo {
  kind: "pglite" | "pg";
  /** PGlite data dir (absolute), or "memory://". Undefined for pg. */
  dataDir?: string;
  label: string;
}

/** Describes the storage the current environment selects, mirroring lib/env's rules. */
export function describeStorage(env: NodeJS.ProcessEnv = process.env): StorageInfo {
  const wanted = env[ENV.DB];
  const kind: "pglite" | "pg" = wanted === "pg" || (!wanted && env[ENV.DATABASE_URL]) ? "pg" : "pglite";
  if (kind === "pg") return { kind, label: "Postgres (DATABASE_URL)" };
  const raw = env[ENV.DATA_DIR] || DEFAULTS.DATA_DIR;
  const dataDir = raw === DEFAULTS.DATA_DIR_MEMORY ? raw : path.resolve(raw);
  return { kind, dataDir, label: `PGlite at ${dataDir}` };
}

/** Prints a boxed notice (used for one-time secrets). */
export function box(title: string, lines: string[]): string {
  const width = Math.max(title.length, ...lines.map((l) => l.length)) + 2;
  const bar = "─".repeat(width);
  const pad = (s: string) => ` ${s}${" ".repeat(width - s.length - 1)}`;
  return [`┌${bar}┐`, `│${pad(title)}│`, `├${bar}┤`, ...lines.map((l) => `│${pad(l)}│`), `└${bar}┘`].join("\n");
}
